export const WS_OWN_ORDERS_CONNECTION_START: "WS_OWN_ORDERS_CONNECTION_START" = 'WS_OWN_ORDERS_CONNECTION_START';
export const WS_OWN_ORDERS_CONNECTION_SUCCESS: "WS_OWN_ORDERS_CONNECTION_SUCCESS" = 'WS_OWN_ORDERS_CONNECTION_SUCCESS';
export const WS_OWN_ORDERS_CONNECTION_ERROR: 'WS_OWN_ORDERS_CONNECTION_ERROR' = 'WS_OWN_ORDERS_CONNECTION_ERROR';
export const WS_OWN_ORDERS_CONNECTION_CLOSED: "WS_OWN_ORDERS_CONNECTION_CLOSED" = 'WS_OWN_ORDERS_CONNECTION_CLOSED'
export const WS_OWN_ORDERS_GET_MESSAGE: "WS_OWN_ORDERS_GET_MESSAGE" = 'WS_OWN_ORDERS_GET_MESSAGE';
export const WS_OWN_ORDERS_SEND_MESSAGE: "WS_OWN_ORDERS_SEND_MESSAGE" = 'WS_OWN_ORDERS_SEND_MESSAGE'