import {createAction} from "@reduxjs/toolkit";

export const WS_PERSONAL_ORDERS_CONNECTION_START: "WS_PERSONAL_ORDERS_CONNECTION_START" = 'WS_PERSONAL_ORDERS_CONNECTION_START';
export const WS_PERSONAL_ORDERS_CONNECTION_SUCCESS: "WS_PERSONAL_ORDERS_CONNECTION_SUCCESS" = 'WS_PERSONAL_ORDERS_CONNECTION_SUCCESS';
export const WS_PERSONAL_ORDERS_CONNECTION_ERROR: 'WS_PERSONAL_ORDERS_CONNECTION_ERROR' = 'WS_PERSONAL_ORDERS_CONNECTION_ERROR';
export const WS_PERSONAL_ORDERS_START_DISCONNECT: "WS_PERSONAL_ORDERS_START_DISCONNECT" = 'WS_PERSONAL_ORDERS_START_DISCONNECT'
export const WS_PERSONAL_ORDERS_CONNECTION_CLOSED: "WS_PERSONAL_ORDERS_CONNECTION_CLOSED" = 'WS_PERSONAL_ORDERS_CONNECTION_CLOSED'
export const WS_PERSONAL_ORDERS_GET_MESSAGE: "WS_PERSONAL_ORDERS_GET_MESSAGE" = 'WS_PERSONAL_ORDERS_GET_MESSAGE';
export const WS_PERSONAL_ORDERS_SEND_MESSAGE: "WS_PERSONAL_ORDERS_SEND_MESSAGE" = 'WS_PERSONAL_ORDERS_SEND_MESSAGE'


export const WSPersonalOrdersFeedStart = createAction<string>(WS_PERSONAL_ORDERS_CONNECTION_START)
export const WSPersonalOrdersFeedClose = createAction(WS_PERSONAL_ORDERS_CONNECTION_CLOSED)
export const WSPersonalOrdersFeedConnected = createAction(WS_PERSONAL_ORDERS_CONNECTION_SUCCESS)
export const WSPersonalOrdersSendMessage = createAction<any>(WS_PERSONAL_ORDERS_SEND_MESSAGE) // не нужен
export const WSPersonalOrdersFeedError = createAction<any>(WS_PERSONAL_ORDERS_CONNECTION_ERROR)
export const WSPersonalOrdersFeedGetMessage = createAction<any>(WS_PERSONAL_ORDERS_GET_MESSAGE)
export const WSPersonalOrdersStartDisconnect= createAction(WS_PERSONAL_ORDERS_START_DISCONNECT)